### ISSUE TITLE
Words to add to the dictionary

### ISSUE THREAD

**Issue by thomasjbradley** [thomasjbradley/markbot#148]
- [x] mistyped
- [x] wikipedia
- [x] figcaption (& maybe other weird tag names)
- [x] Unclosed

**Comment by maddycpierce** [comment]
polaroid

**Comment by JasmineCT** [comment]
color

**Comment by thomasjbradley** [comment]
@JasmineCT Where did the spelling error for `color` come up? Inside a CSS property like `background-color` our just in a regular sentence?

**Comment by JasmineCT** [comment]
More in a regular sentence, when I say" Add color to h1"

**Comment by thomasjbradley** [comment]
The spell checker is set to Canadian English so that’s probably why it’s flagging “color”.

**Comment by Jowens96** [comment]
divs

**Comment by Jowens96** [comment]
blockquote
