### ISSUE TITLE
unit tests?

### ISSUE THREAD

**Issue by titaniumbones** [thomasjbradley/markbot#170]
hi @thomasjbradley , we corresponded briefly about markbot a year ago. It was too much for me then -- and probably still a bit too much for me now! -- but I'm very impressed. I have a couple of questions, asking here in issues for now but happy to move the conversation back over to GH Education if that seems better!

First question -- I'm wondering what it would take to integrate unit testing into markbot. For instance, do you think I could have markbot run a set of mocha or jest tests from a student repo using an html reporter and load the results in a browser tab? 

I am hoping to use unit tests as a kind of online help system for my students. My first thought was to just create an html file with `mocha.js` and `chai.js` loaded from a CDN, and write browser-compatible tests. However, I'm stymied by the lack of access to local files, which makes it very difficult to give meaningful feedback on HTML files from within the browser (though I guess gh-pages might help to get around that).  

I was also hoping to avoid getting students to install npm manually, but I don't see an obvious way around that even with markbot, unless it's somehow practical to use markbot to `npm install` in student repos.  

in any case thank you for your help!

**Comment by thomasjbradley** [comment]
I'm not sure Markbot could do that. Technically, I think we could make it work, but I don't know if you'd get the results you're looking for.

I think it would be fairly simple for you to make an Electron app that does what you want. If the HTML reporter is always the same, the Electron app could load up that HTML file from within itself, then pull in the specific `.js` from the student's repo to run.
