### ISSUE TITLE
replace jar files w/ node alternatives?

### ISSUE THREAD

**Issue by titaniumbones** [thomasjbradley/markbot#171]
Am wondering whether it's remotely possible to replace the external jar tools with node-based alternatives, thus eliminating the need for the JDK.  Only to reduce the number of applications students need to install.

**Comment by thomasjbradley** [comment]
Yeah, that would be wonderful, except I don't believe there's a HTML or CSS validator that isn't built with Java.

There are some Node.js alternatives, yes, but all they do is call to the W3C validator APIs, which will get us blocked/throttled very quickly with the amount of requests all the students would send at one time.

**Comment by titaniumbones** [comment]
/a, I hadn't relaly looked at the node alternatives.  yes of course, sounds like it's not possible, thanks.
