### ISSUE TITLE
Submission Error

### ISSUE THREAD

**Issue by Ibeekuma** [thomasjbradley/markbot#182]
<img width="792" alt="Screenshot 2019-09-24 21 44 28" src="https://user-images.githubusercontent.com/43243602/65608414-2ae37800-df7c-11e9-8ff6-ecf26415f20f.png">

**Comment by thomasjbradley** [comment]
Can you zip up your folder and send it to me?

**Comment by Ibeekuma** [comment]
[exporting-from-illustrator.zip](https://github.com/thomasjbradley/markbot/files/3653782/exporting-from-illustrator.zip)

Please the attached file. 
Thank you.

**Comment by thomasjbradley** [comment]
Hmm. I can’t seem to recreate the same problem in my Markbot. What version are you using? Look in the `Markbot` menu.
