### ISSUE TITLE
Markbot startup stuck loading

### ISSUE THREAD

**Issue by CloudZero458** [thomasjbradley/markbot#208]
says "Starting Up..." but never finishes. this is on Windows 10

**Comment by thomasjbradley** [comment]
What version of JDK is installed on your computer? Markbot doesn’t work so well with newer versions.

https://learn-the-web.algonquindesign.ca/courses/web-design-1/install-all-the-things-windows/#step-8

**Comment by CloudZero458** [comment]
I solved it. I had the wrong version of JDK installed
