### ISSUE TITLE
Default markbot server URL? Sign out?

### ISSUE THREAD

**Issue by kzahel** [thomasjbradley/markbot#68]
If I decide to use the version you distribute, what is the default server URL it uses? (I may just add a DNS entry to my own IP)

Also, is there a way to "sign out" (say you typed your GH username incorrectly)? Perhaps a folder to delete?

**Comment by thomasjbradley** [comment]
The Markbot that I distribute on my website points to Algonquin College's Canvas instance: https://algonquin.instructure.com.

But if you're not planning on handing anything in to Canvas for grades—which I expect you're not—then it’s never used.

---

There’s a menu item to sign out of your GH username:

- Windows: `File > Sign Out`
- Mac: `Markbot > Sign Out`

**Comment by thomasjbradley** [comment]
Although, I suppose that URL isn't entirely correct. Markbot actually submits to a small PHP app: [Markbot Server](/thomasjbradley/markbot-server) which then submits to Canvas.

The current live URL for that is: https://markbot-canvas-proxy.appspot.com

**Comment by kzahel** [comment]
Thanks. I may need to build my own markbot since it's an HTTPS URL. But what should I use for ignoreCommitEmails, if I am not changing your markbot repos, your hey@ email address on your profile?

Do the other activities (such as keyboard commander) report to the same URL by default? e.g. https://markbot-canvas-proxy.appspot.com/grade?%s

**Comment by thomasjbradley** [comment]
These are the emails that you’ll have to ignore if you want to use my repos:

```
    "hey@thomasjbradley.ca",
    "theman@thomasjbradley.ca",
    "bradlet@algonquincollege.com"
```

---

The other activities, like Keyboard Commander, aren't automatically graded. I get the students to complete them in class and I check them right away.
